# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0002_auto_20171111_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperUploadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.IntegerField()),
                ('uploader_id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
